// <auto-generated />
using System;
using DataAccessClientExample.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessClientExample.PostgreSql.Migrations.ExampleSecondDatabase
{
    [DbContext(typeof(ExampleSecondDbContext))]
    partial class ExampleSecondDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessClientExample.DataLayer.ExampleSecondEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ExampleSecondEntities", "dbo");
                });

            modelBuilder.Entity("DataAccessClientExample.DataLayer.ExampleSecondEntity", b =>
                {
                    b.OwnsOne("DataAccessClient.EntityBehaviors.TranslatedProperty<string>", "Code", b1 =>
                        {
                            b1.Property<int>("ExampleSecondEntityId")
                                .HasColumnType("integer");

                            b1.HasKey("ExampleSecondEntityId");

                            b1.ToTable("ExampleSecondEntities", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ExampleSecondEntityId");

                            b1.OwnsMany("DataAccessClient.EntityBehaviors.PropertyTranslation<string>", "Translations", b2 =>
                                {
                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("LocaleId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Translation")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("OwnerId", "Id");

                                    b2.ToTable("ExampleSecondEntity_CodeTranslations", "dbo");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Translations");
                        });

                    b.OwnsOne("TranslatedProperty", "Description", b1 =>
                        {
                            b1.Property<int>("ExampleSecondEntityId")
                                .HasColumnType("integer");

                            b1.HasKey("ExampleSecondEntityId");

                            b1.ToTable("ExampleSecondEntities", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ExampleSecondEntityId");

                            b1.OwnsMany("PropertyTranslation", "Translations", b2 =>
                                {
                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("LocaleId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Translation")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("OwnerId", "Id");

                                    b2.ToTable("ExampleSecondEntity_DescriptionTranslations", "dbo");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Translations");
                        });

                    b.Navigation("Code");

                    b.Navigation("Description");
                });
#pragma warning restore 612, 618
        }
    }
}
