// <auto-generated />
using System;
using DataAccessClientExample.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessClientExample.Migrations.ExampleSecondDatabase
{
    [DbContext(typeof(ExampleSecondDbContext))]
    partial class ExampleSecondDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("DataAccessClientExample.DataLayer.ExampleSecondEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExampleSecondEntities");
                });

            modelBuilder.Entity("DataAccessClientExample.DataLayer.ExampleSecondEntity", b =>
                {
                    b.OwnsOne("DataAccessClient.EntityBehaviors.TranslatedProperty<string>", "Code", b1 =>
                        {
                            b1.Property<int>("ExampleSecondEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.HasKey("ExampleSecondEntityId");

                            b1.ToTable("ExampleSecondEntities");

                            b1.WithOwner()
                                .HasForeignKey("ExampleSecondEntityId");

                            b1.OwnsMany("DataAccessClient.EntityBehaviors.PropertyTranslation<string>", "Translations", b2 =>
                                {
                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<string>("LocaleId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Translation")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnerId", "Id");

                                    b2.ToTable("ExampleSecondEntity_CodeTranslations");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Translations");
                        });

                    b.OwnsOne("DataAccessClient.EntityBehaviors.TranslatedProperty<string>", "Description", b1 =>
                        {
                            b1.Property<int>("ExampleSecondEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.HasKey("ExampleSecondEntityId");

                            b1.ToTable("ExampleSecondEntities");

                            b1.WithOwner()
                                .HasForeignKey("ExampleSecondEntityId");

                            b1.OwnsMany("DataAccessClient.EntityBehaviors.PropertyTranslation<string>", "Translations", b2 =>
                                {
                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<string>("LocaleId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Translation")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnerId", "Id");

                                    b2.ToTable("ExampleSecondEntity_DescriptionTranslations");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Translations");
                        });

                    b.Navigation("Code");

                    b.Navigation("Description");
                });
#pragma warning restore 612, 618
        }
    }
}
