// <auto-generated />
using System;
using DataAccessClientExample.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessClientExample.SqlServer.Migrations.ExampleSecondDatabase
{
    [DbContext(typeof(ExampleSecondDbContext))]
    [Migration("20260114095937_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessClientExample.DataLayer.ExampleSecondEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExampleSecondEntities", (string)null);
                });

            modelBuilder.Entity("DataAccessClientExample.DataLayer.ExampleSecondEntity", b =>
                {
                    b.OwnsOne("DataAccessClient.EntityBehaviors.TranslatedProperty<string>", "Code", b1 =>
                        {
                            b1.Property<int>("ExampleSecondEntityId")
                                .HasColumnType("int");

                            b1.HasKey("ExampleSecondEntityId");

                            b1.ToTable("ExampleSecondEntities");

                            b1.WithOwner()
                                .HasForeignKey("ExampleSecondEntityId");

                            b1.OwnsMany("DataAccessClient.EntityBehaviors.PropertyTranslation<string>", "Translations", b2 =>
                                {
                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("LocaleId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Translation")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnerId", "Id");

                                    b2.ToTable("ExampleSecondEntity_CodeTranslations", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Translations");
                        });

                    b.OwnsOne("TranslatedProperty", "Description", b1 =>
                        {
                            b1.Property<int>("ExampleSecondEntityId")
                                .HasColumnType("int");

                            b1.HasKey("ExampleSecondEntityId");

                            b1.ToTable("ExampleSecondEntities");

                            b1.WithOwner()
                                .HasForeignKey("ExampleSecondEntityId");

                            b1.OwnsMany("PropertyTranslation", "Translations", b2 =>
                                {
                                    b2.Property<int>("OwnerId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("LocaleId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Translation")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("OwnerId", "Id");

                                    b2.ToTable("ExampleSecondEntity_DescriptionTranslations", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.Navigation("Translations");
                        });

                    b.Navigation("Code");

                    b.Navigation("Description");
                });
#pragma warning restore 612, 618
        }
    }
}
